'use client';
import Link from 'next/link'; import {CheckCircle2,AlertTriangle,HelpCircle,ExternalLink,Copy,Check} from 'lucide-react'; import {useState} from 'react';
export function GlassCard({children,className=''}:{children:React.ReactNode,className?:string}){return <div className={`glass rounded-2xl ${className}`}>{children}</div>}
export function Pill({children,tone='green'}:{children:React.ReactNode,tone?:'green'|'orange'|'purple'}){let c={green:'border-lime/30 bg-lime/10 text-lime',orange:'border-amber/30 bg-amber/10 text-amber',purple:'border-violet/30 bg-violet/10 text-violet'}[tone];return <span className={`inline-flex items-center rounded-full border px-3 py-1 text-[11px] font-semibold uppercase tracking-[.16em] ${c}`}>{children}</span>}
export function Button({href,children,secondary=false,className=''}:{href:string,children:React.ReactNode,secondary?:boolean,className?:string}){return <Link className={`focusable inline-flex items-center justify-center rounded-xl px-5 py-3 text-sm font-semibold transition hover:-translate-y-0.5 ${secondary?'border border-white/10 bg-white/5 hover:border-white/25':'bg-lime text-black shadow-[0_0_24px_rgba(158,255,94,.18)] hover:bg-[#b4ff83]'} ${className}`} href={href}>{children}</Link>}
export function CopyButton({value}:{value:string}){const [ok,setOk]=useState(false);return <button aria-label="Copy address" onClick={async()=>{await navigator.clipboard.writeText(value);setOk(true);setTimeout(()=>setOk(false),1400)}} className="focusable rounded-lg border border-white/10 p-2 text-slate-400 hover:text-white">{ok?<Check size={15}/>:<Copy size={15}/>}</button>}
export function ExplorerLink({value,type='account'}:{value:string,type?:'account'|'tx'}){return <a className="focusable inline-flex items-center gap-1.5 text-sm text-lime hover:underline" target="_blank" rel="noreferrer" href={`https://solscan.io/${type}/${value}`}>Solscan <ExternalLink size={13}/></a>}
export function RiskGauge({score,label}:{score:number,label?:string}){const color=score<35?'#9eff5e':score<70?'#ffb45e':'#fb7185';return <div className="relative mx-auto grid h-40 w-40 place-items-center rounded-full" style={{background:`conic-gradient(${color} ${score*3.6}deg,rgba(255,255,255,.07) 0)`}}><div className="grid h-[132px] w-[132px] place-items-center rounded-full bg-[#0b0e13] text-center"><div><b className="text-4xl">{score}</b><span className="text-slate-500">/100</span><p className="mt-1 text-xs uppercase tracking-widest" style={{color}}>{label||classify(score)} risk</p></div></div></div>}
export const classify=(n:number)=>n<35?'Low':n<70?'Medium':'High';
export function Signal({title,status,children}:{title:string,status:'Passed'|'Warning'|'Needs review',children:React.ReactNode}){const I=status==='Passed'?CheckCircle2:status==='Warning'?AlertTriangle:HelpCircle;const c=status==='Passed'?'text-lime':status==='Warning'?'text-amber':'text-violet';return <div className="rounded-xl border border-white/[.07] bg-black/20 p-4"><div className="flex items-center justify-between gap-3"><b className="text-sm">{title}</b><span className={`flex items-center gap-1 text-[11px] ${c}`}><I size={13}/>{status}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{children}</p></div>}
export function SectionTitle({eyebrow,title,copy}:{eyebrow:string,title:string,copy?:string}){return <div className="mb-8 max-w-2xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[.22em] text-lime">{eyebrow}</p><h2 className="text-3xl font-semibold tracking-tight md:text-4xl">{title}</h2>{copy&&<p className="mt-4 leading-7 text-slate-400">{copy}</p>}</div>}
