import {Connection,ParsedInstruction,PublicKey} from '@solana/web3.js';
const RPC_URL=process.env.SOLANA_RPC_URL||'https://api.mainnet-beta.solana.com';
const RPC_TIMEOUT_MS=Number(process.env.SOLANA_RPC_TIMEOUT_MS||8000);
export type DataResult<T>={ok:true;data:T;source:'live';analyzedAt:string}|{ok:false;error:string;code:'RPC_UNAVAILABLE'|'NOT_FOUND'|'INVALID_INPUT';analyzedAt:string};
export const validateSolanaAddress=(value:string)=>{try{return new PublicKey(value).toBase58()===value}catch{return false}};
export const validateTransactionSignature=(value:string)=>/^[1-9A-HJ-NP-Za-km-z]{64,90}$/.test(value);
export const shortAddress=(value:string,n=5)=>value.length>n*2+3?`${value.slice(0,n)}…${value.slice(-n)}`:value;
export const formatDate=(value:number|Date)=>new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(value instanceof Date?value:new Date(value));
function connection(){return new Connection(RPC_URL,{commitment:'confirmed',disableRetryOnRateLimit:true})}
async function withTimeout<T>(work:Promise<T>):Promise<T>{let timer:ReturnType<typeof setTimeout>;const timeout=new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('RPC request timed out')),RPC_TIMEOUT_MS)});try{return await Promise.race([work,timeout])}finally{clearTimeout(timer!)}}
function failure(error:unknown):DataResult<never>{const message=error instanceof Error?error.message:'Unknown RPC error';return {ok:false,error:/429|rate limit/i.test(message)?'The Solana provider is rate-limiting requests. Please retry shortly.':'Live Solana data is temporarily unavailable. Please retry shortly.',code:'RPC_UNAVAILABLE',analyzedAt:new Date().toISOString()}}
export async function getRpcHealth(){const started=Date.now();try{const version=await withTimeout(connection().getVersion());return {ok:true,latencyMs:Date.now()-started,version:version['solana-core'],checkedAt:new Date().toISOString()}}catch{return {ok:false,latencyMs:Date.now()-started,checkedAt:new Date().toISOString()}}}
export interface WalletTransaction{sig:string;time:string;type:string;status:'Success'|'Failed';fee:string}
export interface WalletData{balance:number;count:number;failed:number;tokenAccounts:number;transactions:WalletTransaction[]}
export async function getWalletData(address:string):Promise<DataResult<WalletData>>{if(!validateSolanaAddress(address))return {ok:false,error:'Invalid Solana address.',code:'INVALID_INPUT',analyzedAt:new Date().toISOString()};try{const rpc=connection();const key=new PublicKey(address);const [lamports,sigs,tokens]=await withTimeout(Promise.all([rpc.getBalance(key),rpc.getSignaturesForAddress(key,{limit:20}),rpc.getParsedTokenAccountsByOwner(key,{programId:new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA')})]));return {ok:true,source:'live',analyzedAt:new Date().toISOString(),data:{balance:lamports/1e9,count:sigs.length,failed:sigs.filter(s=>s.err).length,tokenAccounts:tokens.value.length,transactions:sigs.slice(0,8).map(s=>({sig:s.signature,time:s.blockTime?formatDate(s.blockTime*1000):'Time unavailable',type:'Observed transaction',status:s.err?'Failed':'Success',fee:'View details'}))}}}catch(error){return failure(error)}}
export interface TokenData{decimals:number;supply:string;mintAuthority:string|null;freezeAuthority:string|null;initialized:boolean;program:string;largestAccounts:number;topHolderPercent:number|null}
export async function getTokenData(mint:string):Promise<DataResult<TokenData>>{if(!validateSolanaAddress(mint))return {ok:false,error:'Invalid token mint address.',code:'INVALID_INPUT',analyzedAt:new Date().toISOString()};try{const rpc=connection();const key=new PublicKey(mint);const [info,largest]=await withTimeout(Promise.all([rpc.getParsedAccountInfo(key),rpc.getTokenLargestAccounts(key).catch(()=>null)]));if(!info.value)return {ok:false,error:'No account exists for this mint.',code:'NOT_FOUND',analyzedAt:new Date().toISOString()};const parsed=(info.value.data as {parsed?:{type?:string;info?:Record<string,unknown>}}).parsed;if(parsed?.type!=='mint'||!parsed.info)return {ok:false,error:'This address is not an SPL token mint.',code:'NOT_FOUND',analyzedAt:new Date().toISOString()};const i=parsed.info;const supply=Number(i.supply||0);const topRaw=largest?.value[0]?.amount?Number(largest.value[0].amount):0;return {ok:true,source:'live',analyzedAt:new Date().toISOString(),data:{decimals:Number(i.decimals),supply:String(i.supply),mintAuthority:i.mintAuthority?String(i.mintAuthority):null,freezeAuthority:i.freezeAuthority?String(i.freezeAuthority):null,initialized:Boolean(i.isInitialized),program:info.value.owner.toBase58(),largestAccounts:largest?.value.length||0,topHolderPercent:supply>0&&topRaw>=0?topRaw/supply*100:null}}}catch(error){return failure(error)}}
export interface TransactionData{status:'Success'|'Failed';slot:number;time:string;fee:number;programs:string[];instructions:string[];error:string|null}
export async function getTransactionData(signature:string):Promise<DataResult<TransactionData>>{if(!validateTransactionSignature(signature))return {ok:false,error:'Invalid Solana transaction signature.',code:'INVALID_INPUT',analyzedAt:new Date().toISOString()};try{const tx=await withTimeout(connection().getParsedTransaction(signature,{commitment:'confirmed',maxSupportedTransactionVersion:0}));if(!tx)return {ok:false,error:'Transaction was not found at confirmed commitment.',code:'NOT_FOUND',analyzedAt:new Date().toISOString()};const programs=new Set<string>();const instructions=tx.transaction.message.instructions.map((ix,index)=>{if('programId' in ix)programs.add(ix.programId.toBase58());if('parsed' in ix){const parsed=ix as ParsedInstruction;return `${parsed.program}: ${parsed.parsed?.type||'instruction'}`}return `Instruction ${index+1}`});return {ok:true,source:'live',analyzedAt:new Date().toISOString(),data:{status:tx.meta?.err?'Failed':'Success',slot:tx.slot,time:tx.blockTime?formatDate(tx.blockTime*1000):'Time unavailable',fee:(tx.meta?.fee||0)/1e9,programs:[...programs],instructions,error:tx.meta?.err?JSON.stringify(tx.meta.err):null}}}catch(error){return failure(error)}}
export function calculateWalletRiskScore(data:{balance:number;count:number;failed:number}){let score=20;if(data.count===0)score+=10;if(data.balance<.01)score+=5;if(data.count>=20)score+=10;const failureRate=data.count?data.failed/data.count:0;if(failureRate>.25)score+=15;return Math.min(score,100)}
export const classifyRiskLevel=(score:number)=>score<35?'Low':score<70?'Medium':'High';
export function generateWalletExplanation(score:number){return `Available public signals currently produce a ${classifyRiskLevel(score).toLowerCase()} heuristic score. This only reflects the sampled balance and recent signature activity; it does not establish ownership, intent, or complete safety.`}
